server:
  port: 8080

eureka:
  client:
   register-with-eureka: false
   fetch-registry: false
   serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: elasticsearch
    hostname: localhost

spring:
  application:
    name: elasticsearch
    #data:
      #elasticsearch:
        #cluster-nodes: http://localhost:9200
        #cluster-name: service-recherche


cxf:
  path: /api
  jaxrs:
    component-scan: true
    classes-scan-packages: com.palvair.elasticsearch.presentation

elasticsearch:
    host : somewhere

logging:
  level:
    com.palvair: DEBUG
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
