server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: elasticsearch
    hostname: localhost

spring:
  application:
    name: elasticsearch